# Generated by Django 5.0.1 on 2024-01-17 14:13

import datetime
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 1, 17, 14, 13, 47, 976559, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='doctor/')),
                ('location', django_countries.fields.CountryField(max_length=2)),
                ('subtitle', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('price_of_appintment', models.PositiveIntegerField(default=None)),
                ('phone_num', models.PositiveIntegerField(default=None)),
                ('work_hours', models.PositiveIntegerField()),
                ('slug', models.SlugField()),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_doctor', to='doctor.comment')),
                ('specialty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialty_doctor', to='doctor.specialty')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
