# Generated by Django 5.0.1 on 2024-01-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_doctor_review_alter_doctor_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_num',
            field=models.CharField(max_length=50),
        ),
    ]
