# Generated by Django 5.0.1 on 2024-01-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_examination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='examination',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
